[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000

; Prozess-Manager-Einstellungen
pm = dynamic
pm.max_children = 24
pm.start_servers = 4
pm.min_spare_servers = 4
pm.max_spare_servers = 8
pm.max_requests = 750

; Timeout-Einstellungen
request_terminate_timeout = 300
request_slowlog_timeout = 5s
slowlog = /proc/self/fd/2

; Umgebungsvariablen
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

; PHP-Einstellungen
php_admin_value[memory_limit] = 512M
php_admin_value[upload_max_filesize] = 512M
php_admin_value[post_max_size] = 512M
php_admin_value[max_execution_time] = 300
php_admin_value[max_input_time] = 300
php_admin_value[date.timezone] = Europe/Berlin
php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on

; Better diagnostics and health
catch_workers_output = yes
pm.status_path = /status
ping.path = /ping
ping.response = pong
clear_env = no
