package me.ailinux.workspace;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.Locale;

public class MainActivity extends Activity {
    private static final int PICK_TREE=2401,NOTIFY=2402; private StateStore state; private TextView status,folder; private EditText pair; private CheckBox write;
    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){String s=i.getStringExtra("state");if(s!=null)status.setText(s);String code=i.getStringExtra("pair_code");if(code!=null&&!code.isEmpty())showPairCode(code,false);}};
    @Override public void onCreate(Bundle b){super.onCreate(b);state=new StateStore(this);buildUi();handleIntent(getIntent());refresh();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},NOTIFY);}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);handleIntent(intent);}
    @Override protected void onResume(){super.onResume();registerReceiver(receiver,new IntentFilter("me.ailinux.workspace.STATE"),Build.VERSION.SDK_INT>=33?Context.RECEIVER_NOT_EXPORTED:0);refresh();}
    @Override protected void onPause(){try{unregisterReceiver(receiver);}catch(Exception ignored){}super.onPause();}
    private TextView text(String value,int color){TextView v=new TextView(this);v.setText(value);v.setTextColor(color);v.setTextSize(16);v.setPadding(0,8,0,8);return v;}
    private void buildUi(){ScrollView scroll=new ScrollView(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(40,40,40,40);scroll.addView(l);TextView badge=text("AILinux · TriForce MCP",0xff79c0ff);l.addView(badge);TextView title=text("AILinux Workspace",Color.WHITE);title.setTextSize(30);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);l.addView(title);TextView desc=text("The selected folder stays on this device. Native Android routes local shares directly through the foreground MCP executor, independent from browser tab idle/suspension.",0xffb8c1cc);desc.setPadding(0,8,0,24);l.addView(desc);TextView h1=text("1 · Share workspace",Color.WHITE);h1.setTextSize(21);h1.setTypeface(Typeface.DEFAULT,Typeface.BOLD);l.addView(h1);folder=text("",0xffb8c1cc);l.addView(folder);Button choose=button("Choose local folder");choose.setOnClickListener(v->chooseFolder());l.addView(choose);write=new CheckBox(this);write.setText("Read / Write mode");write.setTextColor(Color.WHITE);write.setChecked("write".equals(state.mode()));l.addView(write);TextView h2=text("2 · Pair workspace",Color.WHITE);h2.setTextSize(21);h2.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h2.setPadding(0,26,0,6);l.addView(h2);l.addView(text("Paste an existing pair code, or start the executor and copy the generated code below.",0xff8b949e));pair=new EditText(this);pair.setHint("Pair code");pair.setSingleLine(true);pair.setSelectAllOnFocus(false);pair.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS);pair.setTextColor(Color.WHITE);pair.setHintTextColor(0xff8b949e);pair.setBackgroundColor(0xff161b22);pair.setPadding(20,16,20,16);l.addView(pair);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button copy=button("Copy code");copy.setOnClickListener(v->copyPairCode());actions.addView(copy);Button paste=button("Paste code");paste.setOnClickListener(v->pastePairCode());actions.addView(paste);l.addView(actions);Button start=button("Start / reconnect executor");start.setOnClickListener(v->startExecutor(""));l.addView(start);Button stop=button("Disconnect and revoke lease");stop.setOnClickListener(v->startService(new Intent(this,WorkspaceService.class).setAction(WorkspaceService.ACTION_STOP)));l.addView(stop);Button web=button("Open api.ailinux.me/v1/mcp");web.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://api.ailinux.me/v1/mcp"))));l.addView(web);status=text("",0xff63d471);status.setPadding(0,28,0,0);l.addView(status);setContentView(scroll);scroll.setBackgroundColor(0xff0d1117);}
    private Button button(String text){Button b=new Button(this);b.setText(text);b.setAllCaps(false);return b;}
    private void showPairCode(String code,boolean force){if(code==null||code.isEmpty())return;if(!force&&(pair.hasFocus()||pair.hasSelection()))return;if(code.equals(pair.getText().toString()))return;pair.setText(code);}
    private void copyPairCode(){String code=pair.getText().toString().trim();if(code.isEmpty())code=state.pairCode();if(code.isEmpty()){status.setText("No pair code to copy yet.");return;}((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("AILinux Workspace pair code",code));status.setText("Pair code copied.");}
    private void pastePairCode(){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(!cm.hasPrimaryClip()||cm.getPrimaryClip()==null||cm.getPrimaryClip().getItemCount()==0){status.setText("Clipboard has no pair code.");return;}CharSequence value=cm.getPrimaryClip().getItemAt(0).coerceToText(this);String code=value==null?"":value.toString().trim().toUpperCase(Locale.ROOT);pair.setText(code);pair.setSelection(code.length());if(!code.isEmpty())state.setPairCode(code);status.setText(code.isEmpty()?"Clipboard has no pair code.":"Pair code pasted.");}
    private void chooseFolder(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);startActivityForResult(i,PICK_TREE);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_TREE&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){Uri uri=data.getData();int flags=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);try{getContentResolver().takePersistableUriPermission(uri,flags);}catch(SecurityException e){status.setText("Persistent folder permission failed: "+e.getMessage());return;}state.setTree(uri);state.setMode(write.isChecked()?"write":"read_only");refresh();startExecutor("");}}
    private void handleIntent(Intent intent){if(intent==null||intent.getData()==null)return;Uri u=intent.getData();String handoff="";if("ailinux-workspace".equals(u.getScheme())){String host=u.getHost()==null?"":u.getHost();String code=u.getQueryParameter("code");if("handoff".equals(host))handoff=code==null?"":code;else if("pair".equals(host)&&code!=null)state.setPairCode(code);}else if("api.ailinux.me".equals(u.getHost())){String p=u.getQueryParameter("pair_code");if(p!=null)state.setPairCode(p);}refresh();if(handoff!=null&&!handoff.isEmpty())startExecutor(handoff);}
    private void startExecutor(String handoff){state.setMode(write.isChecked()?"write":"read_only");String p=pair.getText().toString().trim().toUpperCase(Locale.ROOT);if(!p.isEmpty())state.setPairCode(p);Intent i=new Intent(this,WorkspaceService.class).setAction(WorkspaceService.ACTION_START);if(handoff!=null&&!handoff.isEmpty())i.putExtra(WorkspaceService.EXTRA_HANDOFF,handoff);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);status.setText("Executor requested…");}
    private void refresh(){Uri tree=state.tree();folder.setText(tree==null?"No folder shared":"Workspace: "+tree);showPairCode(state.pairCode(),false);write.setChecked("write".equals(state.mode()));if(status.getText().length()==0)status.setText(tree==null?"Choose a folder once; Android keeps the URI grant.":"Ready. Start executor or open a pair/handoff link.");}
}
