"""Legacy compatibility exports for MCP client instructions.

The canonical provider-neutral policy lives in ``agent_instructions.py``.
Historically this module was ChatGPT-specific and contained static OS, host,
tool-count and command assumptions. Keep these names for compatibility without
duplicating the policy.
"""

from .agent_instructions import (
    BINARY_EXEC_GUIDANCE,
    MCP_CORE_INSTRUCTIONS,
    TASK_RUNNER_GUIDANCE,
    build_mcp_instructions,
)

SYSTEM_INSTRUCTIONS = build_mcp_instructions()
TASK_RUNNER_DESCRIPTION = TASK_RUNNER_GUIDANCE
BINARY_EXEC_DESCRIPTION = BINARY_EXEC_GUIDANCE

INIT_PROMPT = {
    "name": "ailinux_triforce",
    "description": "Current operating guidance for AILinux TriForce MCP clients",
    "arguments": [],
    "content": build_mcp_instructions(),
}

# Compatibility symbol. The live task reference is generated by task_runner.
QUICK_REFERENCE = {
    "discovery": "Use task_reference(action='quick_reference') for the live command reference."
}
